- titulo: "Livro A Vida Invisível de Addie LaRue"
  categoria: "livros"
  preco: "50,00"
  slug: "addie-larue-ve-schwab"
  status: "disponível"
  link_olx: "https://www.olx.com.br/vi/1498932233"
  imagem: "assets/imagens/addie.jpg"
  descricao: "Fantasia histórica emocionante sobre uma mulher que vive séculos sendo esquecida por todos. Novo ainda lacrado."

- titulo: "Kit iPad 9ª Geração 64GB + Apple Pencil Original"
  categoria: "apple"
  preco: "2099,00"
  slug: "kit-ipad-9-apple-pencil"
  status: "disponível"
  link_olx: "https://www.olx.com.br/vi/1504284791"
  imagem: "assets/imagens/ipad.webp"
  descricao: "Kit iPad 9ª Geração 64GB Wi-Fi + Apple Pencil 1ª Geração | Completo | Excelente Estado"

- titulo: "Livro Verity - Colleen Hoover"
  categoria: "livros"
  preco: "40,00"
  slug: "verity-colleen-hoover"
  status: "indisponível"
  link_olx: "https://www.olx.com.br/vi/1498928309"
  imagem: "assets/imagens/verity.jpg"
  descricao: "Thriller psicológico fenomenal de Colleen Hoover. Novo, ainda lacrado. Filme anunciado com Anne Hathaway!"
