- titulo: "Verity"
  categoria: "livros"
  preco: "40,00"
  slug: "verity-colleen-hoover"
  status: "disponível"
  link_olx: "https://www.olx.com.br/vi/1498928309"
  imagem: "assets/imagens/verity.jpg"
  descricao: "Thriller psicológico fenomenal de Colleen Hoover. Novo, ainda lacrado. Filme anunciado com Anne Hathaway!"

- titulo: "A Vida Invisível de Addie LaRue"
  categoria: "livros"
  preco: "45,00"
  slug: "addie-larue-ve-schwab"
  status: "disponível"
  link_olx: "https://www.olx.com.br/vi/1498932233"
  imagem: "assets/imagens/addie.jpg"
  descricao: "Fantasia histórica emocionante sobre uma mulher que vive séculos sendo esquecida por todos. Novo ainda lacrado."
